check if working

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,5 +59,5 @@ jobs:
         run: docker compose down -v
 
       # שגיאה מכוונת: אם תסיר את השורה הזו, השגיאה תיפתר
-      - name: Intentional failure (remove this line later)
-        run: exit 1
+      #- name: Intentional failure (remove this line later)
+      #  run: exit 1
